bike = 'yamaha'
c = 10
print("Is bike == 'yamaha'? I predict True")
print(bike == 'yamaha')
print("Is bike == 'honda'? I predict False")
print(bike == 'honda')
print("Is c >= 5? I predict True")
print(c >= 5)
print("Is c <= 5? I predict False")
print(c <= 5)
a = ['audi', 'bmw']
print("Is 'audi' in a? I predict True")
print('audi' in a)
print("Is 'subaru' in a? I predict False")
print('subaru' in a)
print("Is 'volvo' is not a? I predict True")
print('volvo' not in a)
print("Is 'bmw' is not a? I predict False")
print('bmw' not in a)
print("Is c != 5? I predict True")
print(c != 5)
print("Is c != 10? I predict False")
print(c != 10)
