guests = ['stallin', 'einstein', 'nevzorov']
print(guests[0] + ' zahodi na uzhin!')
print(guests[1] + ' zahodi na uzhin!')
print(guests[2] + ' zahodi na uzhin!')
print(guests[0])
guests[0] = 'hoking'
print(guests[0] + ' zahodi na uzhin!')
print(guests[1] + ' zahodi na uzhin!')
print(guests[2] + ' zahodi na uzhin!')
print('my rastem')
guests.insert(0, 'pavlov')
guests.insert(2, 'shnurov')
guests.append('tolstoy')
print(guests[0] + ' zahodi na uzhin!')
print(guests[1] + ' zahodi na uzhin!')
print(guests[2] + ' zahodi na uzhin!')
print(guests[3] + ' zahodi na uzhin!')
print(guests[4] + ' zahodi na uzhin!')
print(guests[5] + ' zahodi na uzhin!')
print("Priglasheno " + str(len(guests)) + " gostey")
print('ostanutsya dvoe')
popping_guests = guests.pop()
print('sorry ' + popping_guests)
popping_guests = guests.pop()
print('sorry ' + popping_guests)
popping_guests = guests.pop()
print('sorry ' + popping_guests)
popping_guests = guests.pop()
print('sorry ' + popping_guests)
print(guests[0] + ' vse v sile')
print(guests[1] + ' vse v sile')
del guests[0]
del guests[0]
print(guests)
